services:
  # 1. Dynamic bikes data scraping
  scraper-bikes:
    build: .
    container_name: bikes-bot
    command: python data_scripts/automation/2_scraper_bikes.py
    restart: always # Ensure the scraper automatically recovers from crashes
    deploy:
      resources:
        limits:
          memory: 200M  # Prevent resource exhaustion on the EC2 instance
          cpus: '0.40'
    volumes:
      - ./dbinfo.py:/app/dbinfo.py  # Inject database credentials securely from the host
    environment:
      - TZ=Europe/Dublin # Align container logs with local Irish time

  # 2. Dynamic weather data scraping
  scraper-weather:
    build: .
    container_name: weather-bot
    command: python data_scripts/automation/3_scraper_weather.py
    restart: always
    deploy:
      resources:
        limits:
          memory: 200M
          cpus: '0.40'
    volumes:
      - ./dbinfo.py:/app/dbinfo.py
    environment:
      - TZ=Europe/Dublin

  # 3. Dynamic weather data scraping
  flask-backend:
    build: .
    container_name: dublin-bikes-api
    restart: always
    ports:
      - "80:5000" # External network port 80 corresponds to port 5000 inside the container, bypassing campus network blocking.
    deploy:
      resources:
        limits:
          memory: 500M  # Higher memory limit to handle concurrent API requests
          cpus: '0.60'
    volumes:
      - ./dbinfo.py:/app/dbinfo.py
    env_file:
      - .env
    environment:
      - TZ=Europe/Dublin
      - FLASK_ENV=production
